services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/knth/jellyfin/lib:/config
      - /home/knth/jellyfin/tvshows:/data/tvshows
      - /home/knth/jellyfin/animes:/data/animes
      - /home/knth/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.zenylium.xyz`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8089"
      - "traefik.http.services.jellyfin.loadbalancer.server.scheme=https" # else: Client sent an HTTP request to an HTTPS server.
  
networks:
  proxy:
    external: true
