version: "3"
  
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/CEST
    volumes:
      - /home/knth/docker/config/nextcloud/appdata:/config
      - /home/knth/nextcloud-data:/data
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.zenylium.xyz`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=`https://(.*)/.well-known/(?:card|cal)dav`"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=`https://$${1}/remote.php/dav`"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud_redirectregex"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https" # else: Client sent an HTTP request to an HTTPS server.
  
networks:
  proxy:
    external: true
